document.addEventListener('DOMContentLoaded', () => {
    const quotes = [
        "A teacher plants the seeds of knowledge that grow forever.",
        "Teaching is the art of awakening the natural curiosity of young minds.",
        "A teacher's influence touches eternity; no one can tell where it stops.",
        "You light the path for future generations with every lesson you teach.",
        "The best teachers inspire students to become their best selves.",
        "Your passion for teaching fuels a lifetime of learning.",
        "A teacher's heart is where wisdom and compassion meet.",
        "You shape minds, nurture dreams, and build futures.",
        "Every child you teach is a step toward a brighter world.",
        "Your guidance turns potential into achievement.",
        "Teachers don't just teach; they create possibilities.",
        "Your classroom is a canvas where dreams take shape.",
        "A teacher's love for learning sparks a fire in students.",
        "You are the architect of minds and the builder of futures.",
        "Teaching is the greatest act of optimism.",
        "Your patience transforms struggles into successes.",
        "A teacher’s wisdom is the key to unlocking a child’s potential.",
        "You inspire students to soar beyond their horizons.",
        "Every lesson you teach is a gift to the world.",
        "Your dedication turns ordinary moments into extraordinary learning.",
        "A teacher’s encouragement is the wind beneath a student’s wings.",
        "You make learning an adventure that never ends.",
        "Your belief in students makes them believe in themselves.",
        "Teachers are the unsung heroes of every success story.",
        "Your lessons ripple through time, shaping the future.",
        "A teacher’s kindness leaves a mark on every heart.",
        "You turn curiosity into knowledge and dreams into reality.",
        "Your classroom is where hope and opportunity bloom.",
        "A teacher’s legacy is written in the lives they touch.",
        "You empower students to write their own stories.",
        "Your passion for teaching is a beacon of light for all.",
        "Teachers build bridges from dreams to reality.",
        "Your guidance helps students find their true north.",
        "A teacher’s love is the foundation of every achievement.",
        "You make every student feel like they matter.",
        "Your lessons are the stepping stones to greatness.",
        "A teacher’s wisdom is a gift that keeps on giving.",
        "You inspire students to dream big and work hard.",
        "Your classroom is a sanctuary of learning and growth.",
        "Teachers are the spark that ignites a love for learning.",
        "Your patience turns challenges into triumphs.",
        "A teacher’s heart is the compass for a student’s journey.",
        "You help students discover the power within them.",
        "Your dedication shapes minds and changes lives.",
        "Teachers are the gardeners of human potential.",
        "Your encouragement helps students climb mountains.",
        "A teacher’s smile can light up a classroom.",
        "You make learning a joyful journey for every student.",
        "Your wisdom guides students through life’s challenges.",
        "Teachers are the heroes who shape tomorrow’s leaders.",
        "Your passion makes every lesson unforgettable.",
        "A teacher’s care turns dreams into realities.",
        "You inspire students to reach for the stars.",
        "Your guidance is the foundation of every success.",
        "Teachers are the torchbearers of knowledge and hope.",
        "Your lessons are the building blocks of a better world.",
        "A teacher’s faith in students creates miracles.",
        "You help students find their voice and their purpose.",
        "Your dedication is the heartbeat of education.",
        "Teachers are the sculptors of future generations.",
        "Your encouragement makes every student shine.",
        "A teacher’s wisdom lights the path to success.",
        "You turn every classroom into a place of wonder.",
        "Your passion for teaching inspires lifelong learning.",
        "Teachers are the roots that help students grow tall.",
        "Your guidance helps students navigate life’s journey.",
        "A teacher’s love is the spark that ignites potential.",
        "You make every student feel capable of greatness.",
        "Your lessons are the keys to unlocking dreams.",
        "Teachers are the pillars of a thriving society.",
        "Your patience helps students overcome every obstacle.",
        "A teacher’s heart is where knowledge and kindness unite.",
        "You inspire students to create their own paths.",
        "Your dedication is the foundation of every success story.",
        "Teachers are the dream-weavers of tomorrow.",
        "Your encouragement helps students conquer their fears.",
        "A teacher’s guidance is a gift that lasts a lifetime.",
        "You make learning a celebration of discovery.",
        "Your passion turns classrooms into places of magic.",
        "Teachers are the catalysts for change and growth.",
        "Your wisdom helps students find their true potential.",
        "A teacher’s love is the fuel for every dream.",
        "You inspire students to believe in their own power.",
        "Your lessons are the threads that weave a brighter future.",
        "Teachers are the guardians of knowledge and hope.",
        "Your patience turns dreams into realities.",
        "A teacher’s heart is the spark that lights up lives.",
        "You help students build wings to soar high.",
        "Your dedication makes every lesson a masterpiece.",
        "Teachers are the stars that guide students home.",
        "Your encouragement transforms lives every day.",
        "A teacher’s wisdom is the light in the darkness.",
        "You inspire students to write their own destinies.",
        "Your passion for teaching is a gift to the world.",
        "Teachers are the architects of a better tomorrow.",
        "Your guidance helps students find their true calling.",
        "A teacher’s love is the foundation of every dream.",
        "You make every student feel like they can change the world."
    ];
    const jokes = [
        "Why did the teacher wear sunglasses? Because her class was so bright!",
        "Why was the math book sad? It had too many problems!",
        "What’s a teacher’s favorite nation? Expla-nation!",
        "Why did the teacher go to art school? To learn how to draw a better 'line'!",
        "What do you call a teacher who forgets names? Professor Who?",
        "Why don’t teachers trust stairs? They’re always up to something!",
        "What’s a teacher’s favorite dessert? A slice of pi!",
        "Why was the teacher cross-eyed? She couldn’t control her pupils!",
        "What did the teacher say to the pencil? Write on!",
        "Why did the teacher bring a ladder to class? To take learning to the next level!",
        "What’s a teacher’s favorite music? Anything with good 'notes'!",
        "Why don’t teachers use pencils? They prefer to make a permanent mark!",
        "What do you call a teacher with no students? A marker!",
        "Why did the teacher go to the gym? To improve her 'class' strength!",
        "What’s a teacher’s favorite animal? A spelling bee!",
        "Why did the teacher write on the window? To make the lesson clear!",
        "What did the teacher say at the beach? Don’t let the tide take your homework!",
        "Why are teachers good at hide and seek? They always know where you’re not paying attention!",
        "What’s a teacher’s favorite flower? A know-lily!",
        "Why did the teacher bring a broom to class? To sweep away confusion!",
        "What do you call a teacher who loves puns? A wordplay wizard!",
        "Why don’t teachers use chalkboards anymore? They’ve moved to the digital boardroom!",
        "What’s a teacher’s favorite sport? Class-ics!",
        "Why did the teacher sit on a clock? To make time for learning!",
        "What do teachers dream about? A class that’s always on point!",
        "Why did the teacher love geometry? She could always find the right angle!",
        "What’s a teacher’s favorite drink? Tea-cher’s special blend!",
        "Why was the teacher always calm? She had a lot of 'class' control!",
        "What do you call a teacher who loves history? A past master!",
        "Why did the teacher carry a ruler? To keep things in line!",
        "What’s a teacher’s favorite season? Back-to-school season!",
        "Why don’t teachers play chess? They’re afraid of any move that involves a bishop!",
        "What did the teacher say to the noisy class? Let’s have some quiet-tude!",
        "Why did the teacher love science? She enjoyed sparking curiosity!",
        "What’s a teacher’s favorite game? Quiz-ardry!",
        "Why did the teacher bring a flashlight? To shine light on tough topics!",
        "What do you call a teacher who loves to sing? A pitch-perfect professor!",
        "Why don’t teachers use erasers? They believe in learning from mistakes!",
        "What’s a teacher’s favorite fruit? A learn-ange!",
        "Why did the teacher go to space? To teach the stars how to shine!",
        "What do you call a teacher who loves books? A lit-erature legend!",
        "Why did the teacher join a band? To keep the class in rhythm!",
        "What’s a teacher’s favorite tool? A knowledge hammer!",
        "Why did the teacher love puzzles? She enjoyed putting knowledge together!",
        "What do you call a teacher who’s always prepared? A lesson planner extraordinaire!",
        "Why don’t teachers get lost? They always follow the curriculum map!",
        "What’s a teacher’s favorite color? Chalkboard green!",
        "Why did the teacher bring a compass? To guide students in the right direction!",
        "What do you call a teacher who loves math? A number cruncher!",
        "Why did the teacher stay late? To grade the day’s success!"
    ];

    document.getElementById('quote').textContent = quotes[Math.floor(Math.random() * quotes.length)];
    document.getElementById('jokeBtn').addEventListener('click', () => {
        document.getElementById('joke').textContent = jokes[Math.floor(Math.random() * jokes.length)];
        document.getElementById('joke').classList.add('animate-slide-up');
        setTimeout(() => document.getElementById('joke').classList.remove('animate-slide-up'), 800);
    });
    document.getElementById('songBtn').addEventListener('click', () => {
        const audio = document.getElementById('song');
        audio.src = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3';
        audio.play();
        setTimeout(() => audio.pause(), 30000);
    });
    document.getElementById('logoutBtn').addEventListener('click', () => {
        localStorage.removeItem('currentUser');
        window.location.href = 'login.html';
    });
});